#!/usr/bin/python3

def factorize(num):
    for p in range(2, num // 2 + 1):
        if num % p == 0:
            q = num // p
            print(f"{num}={q}*{p}")
            return

    print(f"{num} is a prime number.")


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]

    try:
        with open(file_path, "r") as file:
            for line in file:
                num = int(line)
                factorize(num)
    except FileNotFoundError:
        print("Error opening file.")
        sys.exit(1)
